### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CharlesHunter** [p4535992/MountUp#17]
**Module Version:** v3.2.25
**Foundry Version:** Version 10 Build 284

When dismounting a token, the following exceptions are thrown:
```
Error: TokenDocument5e [ZEeZJVSNg71HI1GP] Model Validation Errors
[TokenDocument5e.width]: must be a finite number
[TokenDocument5e.height]: must be a finite number
[Detected 1 package: foundryvtt-mountup]
    at SchemaField._validateType (commons.js:3630:15)
    at SchemaField.validate (commons.js:3357:37)
    at TokenDocument5e.validate (commons.js:4994:35)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12560:13)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12507:33)
    at ClientDatabaseBackend.update (commons.js:6296:33)
    at async TokenDocument5e.updateDocuments (commons.js:5652:23)
    at async TokenDocument5e.update (commons.js:5749:23)
    at async MountManager.restoreRiderSize (mountManager.js:234:13)
onError @ foundry.js:711
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
_preUpdateDocumentArray @ foundry.js:12563
_updateEmbeddedDocuments @ foundry.js:12507
update @ commons.js:6296
await in update (async)
updateDocuments @ commons.js:5652
update @ commons.js:5749
restoreRiderSize @ mountManager.js:234
doRemoveMount @ mountManager.js:164
await in doRemoveMount (async)
dismount @ mountManager.js:99
(anonymous) @ mountHud.js:96
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
mountManager.js:220 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'actor')
[Detected 1 package: foundryvtt-mountup]
    at MountManager.restoreRiderSize (mountManager.js:220:35)
    at MountManager.doRemoveMount (mountManager.js:164:14)
```

**Comment by shecrio** [comment]
This error also prevents tokens from returning to their previous size, if mounting them resized them.
